language: ruby
rvm:
  - 2.7.1
env:
  RAILS_ENV=test
cache:
  - bundler
  - yarn
services:
  - postgresql
  - xvfb
before_install:
  - nvm install --lts
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - rails db:create
  - bundle exec rails db:schema:load
script:
  - rails test
  - rails test:system
